---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- name: define wsgi package name
  set_fact:
    wsgi_package_name: "{{ _wsgi_package_name }}"
  when: wsgi_package_name is not defined

- name: install mod_wsgi
  yum:
    name: "{{ wsgi_package_name }}"
    state: present
  tags:
    - python
    - wsgi
    - packages

- name: configure main mod_wsgi settings
  template:
    src: wsgi.conf.j2
    dest: /etc/httpd/conf.d/wsgi.conf
    mode: 0644
    owner: root
    group: root
  notify: restart httpd
  tags:
    - python
    - wsgi
    - configuration

- name: configure vhost mod_wsgi settings
  template:
    src: vhost.wsgi.conf.j2
    dest: "/etc/httpd/conf.d/vhost_{{ item.key }}.conf.d/wsgi.conf"
    mode: 0644
    owner: root
    group: root
  with_dict: "{{ wsgi_apps }}"
  tags:
    - python
    - wsgi
    - configuration
