---
- name: install mod_wsgi
  yum: name=mod_wsgi state=present
  when: python_base_name == 'python'
  tags:
    - python
    - wsgi
    - packages

- name: configure main mod_wsgi settings
  template: src=wsgi.conf.j2  dest=/etc/httpd/conf.d/wsgi.conf mode=0644 owner=root group=root
  when: python_base_name == 'python'
  notify: restart httpd
  tags:
    - python
    - wsgi
    - configuration

- name: configure vhost mod_wsgi settings
  template: src=vhost.wsgi.conf.j2 dest="/etc/httpd/conf.d/vhost_{{ item.key }}.conf.d/wsgi.conf" mode=0644 owner=root group=root
  with_dict: "{{ wsgi_apps }}"
